spring.application.name=hackathon
spring.config.import=optional:file:.env[.properties]
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
